name: Development (Admin)
values:
  - key: base_url
    value: 'https://cpapi.jamesnguyen831.id.vn/api'
  - key: username
    value: admin
  - key: password
    value: password123
  - key: token
    value: ''
color: 0
